import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Genel Site Ayarları",
  type: "document",
  groups: [
    { name: "general", title: "Genel" },
    { name: "navigation", title: "Menü" },
    { name: "social", title: "Sosyal & İletişim" },
    { name: "header", title: "Header" },
    { name: "footer", title: "Footer" },
    { name: "labels", title: "Arayüz Metinleri" },
    { name: "productDetail", title: "Ürün Detayı" },
    { name: "seo", title: "SEO" },
    { name: "system", title: "Hata / Yükleniyor" },
  ],
  fields: [
    defineField({
      name: "siteTitle",
      title: "Site Başlığı",
      type: "string",
      initialValue: "Yüksel'in Hobileri",
      group: "general",
    }),

    // NAVIGATION
    defineField({
      name: "navLinks",
      title: "Menü linkleri",
      type: "array",
      group: "navigation",
      of: [
        {
          type: "object",
          name: "navLink",
          fields: [
            { name: "label", title: "Etiket", type: "string" },
            { name: "href", title: "URL", type: "string" },
          ],
          preview: {
            select: { title: "label", subtitle: "href" },
          },
        },
      ],
      initialValue: [
        { _key: "n1", label: "Ana Sayfa", href: "/" },
        { _key: "n2", label: "Ürünler", href: "/urunler" },
        { _key: "n3", label: "Hakkımda", href: "/hakkimizda" },
        { _key: "n4", label: "SSS", href: "/sss" },
      ],
    }),

    // SOCIAL
    defineField({
      name: "instagramUrl",
      title: "Instagram URL",
      type: "url",
      initialValue: "https://www.instagram.com/ykslbcl/",
      group: "social",
    }),
    defineField({
      name: "instagramHandle",
      title: "Instagram kullanıcı adı",
      type: "string",
      initialValue: "@ykslbcl",
      group: "social",
    }),
    defineField({
      name: "whatsappNumber",
      title: "WhatsApp Numarası (opsiyonel)",
      type: "string",
      group: "social",
    }),
    defineField({
      name: "shopierStoreUrl",
      title: "Shopier Mağaza Linki (opsiyonel)",
      type: "url",
      group: "social",
    }),

    // HEADER
    defineField({
      name: "headerTagline",
      title: "Logo altı etiket (el yazısı)",
      type: "string",
      initialValue: "el emeği örgü",
      group: "header",
    }),

    // FOOTER
    defineField({
      name: "footerStudioLabel",
      title: "Footer atölye etiketi",
      type: "string",
      initialValue: "/ Atölye",
      group: "footer",
    }),
    defineField({
      name: "footerTagline",
      title: "Footer slogan (el yazısı)",
      type: "string",
      initialValue: "her ilmek bir hikaye",
      group: "footer",
    }),
    defineField({
      name: "footerDescription",
      title: "Footer açıklama",
      type: "text",
      rows: 3,
      group: "footer",
    }),
    defineField({
      name: "footerContactTitle",
      title: "Footer iletişim başlığı",
      type: "string",
      initialValue: "iletişim",
      group: "footer",
    }),
    defineField({
      name: "footerContactLine1",
      title: "Footer iletişim satır 1",
      type: "string",
      initialValue: "Sipariş için Instagram'dan yazın.",
      group: "footer",
    }),
    defineField({
      name: "footerContactLine2",
      title: "Footer iletişim satır 2",
      type: "string",
      initialValue: "Türkiye'nin her yerine kargo.",
      group: "footer",
    }),
    defineField({
      name: "footerSignature",
      title: "Footer alt yazı (el yazısı)",
      type: "string",
      initialValue: "sevgiyle örüldü",
      group: "footer",
    }),
    defineField({
      name: "footerNavTitle",
      title: "Footer “sayfalar” başlığı",
      type: "string",
      initialValue: "sayfalar",
      group: "footer",
    }),

    // UI LABELS
    defineField({
      name: "instagramHeaderLabel",
      title: "Header Instagram butonu",
      type: "string",
      initialValue: "Instagram",
      group: "labels",
    }),
    defineField({
      name: "instagramButtonLabel",
      title: "Instagram butonu (genel)",
      type: "string",
      initialValue: "Instagram'dan yaz",
      group: "labels",
    }),
    defineField({
      name: "instagramProductButtonLabel",
      title: "Instagram butonu (ürün)",
      type: "string",
      initialValue: "Instagram'dan sipariş ver",
      group: "labels",
    }),
    defineField({
      name: "instagramDmTemplate",
      title: "Instagram DM şablonu",
      description: 'Ürün adı için {title} kullanın. Örn: Merhaba, "{title}" hakkında bilgi almak istiyorum.',
      type: "string",
      initialValue: 'Merhaba, "{title}" hakkında bilgi almak istiyorum.',
      group: "labels",
    }),
    defineField({
      name: "shopierButtonLabel",
      title: "Shopier butonu",
      type: "string",
      initialValue: "Shopier'dan satın al",
      group: "labels",
    }),
    defineField({
      name: "whatsappButtonLabel",
      title: "WhatsApp butonu",
      type: "string",
      initialValue: "WhatsApp'tan yaz",
      group: "labels",
    }),
    defineField({
      name: "breadcrumbHomeLabel",
      title: "Breadcrumb — Ana sayfa",
      type: "string",
      initialValue: "Ana sayfa",
      group: "labels",
    }),
    defineField({
      name: "breadcrumbProductsLabel",
      title: "Breadcrumb — Ürünler",
      type: "string",
      initialValue: "Ürünler",
      group: "labels",
    }),
    defineField({
      name: "backToProductsLabel",
      title: "Ürün detayı — geri linki",
      type: "string",
      initialValue: "← Tüm çantalar",
      group: "labels",
    }),
    defineField({
      name: "allCategoriesLabel",
      title: "Kategori filtresi — Hepsi",
      type: "string",
      initialValue: "Hepsi",
      group: "labels",
    }),
    defineField({
      name: "giftReadyLabel",
      title: "Hediye paketli rozeti",
      type: "string",
      initialValue: "Hediye paketli",
      group: "labels",
    }),
    defineField({
      name: "saleBadgeTemplate",
      title: "İndirim rozeti şablonu",
      description: "Yüzde için {percent} kullanın.",
      type: "string",
      initialValue: "%{percent} indirim",
      group: "labels",
    }),
    defineField({
      name: "statusAvailableLabel",
      title: "Durum — Stokta",
      type: "string",
      initialValue: "Stokta",
      group: "labels",
    }),
    defineField({
      name: "statusMadeToOrderLabel",
      title: "Durum — Sipariş üzerine",
      type: "string",
      initialValue: "Sipariş üzerine",
      group: "labels",
    }),
    defineField({
      name: "statusSoldLabel",
      title: "Durum — Satıldı",
      type: "string",
      initialValue: "Satıldı",
      group: "labels",
    }),
    defineField({
      name: "imagePlaceholderLabel",
      title: "Fotoğraf yok metni",
      type: "string",
      initialValue: "fotoğraf yakında",
      group: "labels",
    }),
    defineField({
      name: "relatedProductsHandwritten",
      title: "Benzer ürünler — el yazısı",
      type: "string",
      initialValue: "bunlar da hoşuna gidebilir",
      group: "labels",
    }),
    defineField({
      name: "relatedProductsTitle",
      title: "Benzer ürünler — başlık",
      type: "string",
      initialValue: "Benzer çantalar",
      group: "labels",
    }),
    defineField({
      name: "productNotFoundTitle",
      title: "Ürün bulunamadı (SEO)",
      type: "string",
      initialValue: "Çanta bulunamadı",
      group: "labels",
    }),
    defineField({
      name: "productMetaDescriptionSuffix",
      title: "Ürün meta açıklama eki",
      description: "Fiyat sonrası ek. Örn: Instagram'dan sipariş verin.",
      type: "string",
      initialValue: "Instagram'dan sipariş verin.",
      group: "labels",
    }),

    // PRODUCT DETAIL
    defineField({
      name: "labelDimensions",
      title: "Etiket — Boyut",
      type: "string",
      initialValue: "Boyut",
      group: "productDetail",
    }),
    defineField({
      name: "labelMaterial",
      title: "Etiket — Malzeme",
      type: "string",
      initialValue: "Malzeme",
      group: "productDetail",
    }),
    defineField({
      name: "labelCare",
      title: "Etiket — Bakım",
      type: "string",
      initialValue: "Bakım",
      group: "productDetail",
    }),
    defineField({
      name: "labelColors",
      title: "Etiket — Renk seçenekleri",
      type: "string",
      initialValue: "Renk seçenekleri",
      group: "productDetail",
    }),
    defineField({
      name: "detailNoteHandwritten",
      title: "Ürün detayı not başlığı (el yazısı)",
      type: "string",
      initialValue: "küçük bir not",
      group: "productDetail",
    }),
    defineField({
      name: "detailNoteText",
      title: "Ürün detayı not metni",
      type: "text",
      rows: 3,
      group: "productDetail",
    }),

    // SEO
    defineField({
      name: "seoTitleSuffix",
      title: "SEO başlık eki",
      type: "string",
      initialValue: "El Emeği Örgü Çantalar",
      group: "seo",
    }),
    defineField({
      name: "seoDescription",
      title: "SEO açıklama",
      type: "text",
      rows: 3,
      group: "seo",
    }),
    defineField({
      name: "seoKeywords",
      title: "SEO anahtar kelimeler",
      type: "array",
      of: [{ type: "string" }],
      group: "seo",
    }),
    defineField({
      name: "ogDescription",
      title: "Open Graph açıklama",
      type: "text",
      rows: 2,
      group: "seo",
    }),

    // SYSTEM
    defineField({
      name: "errorHandwritten",
      title: "Hata — el yazısı",
      type: "string",
      initialValue: "bir aksilik oldu",
      group: "system",
    }),
    defineField({
      name: "errorTitle",
      title: "Hata — başlık",
      type: "string",
      initialValue: "Sayfa yüklenemedi",
      group: "system",
    }),
    defineField({
      name: "errorText",
      title: "Hata — açıklama",
      type: "text",
      rows: 2,
      initialValue: "Sanırım bir ilmek kaçtı. Bir dakika sonra tekrar dene.",
      group: "system",
    }),
    defineField({
      name: "errorRetryLabel",
      title: "Hata — tekrar dene",
      type: "string",
      initialValue: "Tekrar dene",
      group: "system",
    }),
    defineField({
      name: "errorHomeLabel",
      title: "Hata — ana sayfa",
      type: "string",
      initialValue: "Ana sayfaya dön",
      group: "system",
    }),
    defineField({
      name: "notFoundHandwritten",
      title: "404 — el yazısı",
      type: "string",
      initialValue: "aman",
      group: "system",
    }),
    defineField({
      name: "notFoundTitle",
      title: "404 — başlık",
      type: "string",
      initialValue: "Sayfa bulunamadı",
      group: "system",
    }),
    defineField({
      name: "notFoundText",
      title: "404 — açıklama",
      type: "text",
      rows: 2,
      initialValue: "Aradığın sayfa burada değil. Belki ipucu kayboldu.",
      group: "system",
    }),
    defineField({
      name: "notFoundHomeLabel",
      title: "404 — ana sayfa butonu",
      type: "string",
      initialValue: "Ana sayfaya dön",
      group: "system",
    }),
    defineField({
      name: "loadingHandwritten",
      title: "Yükleniyor — el yazısı",
      type: "string",
      initialValue: "örülüyor...",
      group: "system",
    }),
    defineField({
      name: "loadingText",
      title: "Yükleniyor — alt metin",
      type: "string",
      initialValue: "Sayfa hazırlanıyor",
      group: "system",
    }),
  ],
  preview: {
    prepare() {
      return { title: "Genel Site Ayarları" };
    },
  },
});
